export type LoteriaCard = { n: number; name: string; emoji: string; verso: string }

/** Las 54 cartas clásicas (la 26 y la 38 cambiadas para evitar estereotipos) */
export const LOTERIA: LoteriaCard[] = [
  { n: 1, name: 'El Gallo', emoji: '🐓', verso: 'El que le cantó a San Pedro no le volverá a cantar.' },
  { n: 2, name: 'El Diablito', emoji: '😈', verso: 'Pórtate bien, cuatito, si no te lleva el coloradito.' },
  { n: 3, name: 'La Dama', emoji: '💃', verso: 'Puliendo el paso por toda la calle real.' },
  { n: 4, name: 'El Catrín', emoji: '🎩', verso: 'Don Ferruco en la alameda, su bastón quería tirar.' },
  { n: 5, name: 'El Paraguas', emoji: '☂️', verso: 'Para el sol y para el agua.' },
  { n: 6, name: 'La Sirena', emoji: '🧜‍♀️', verso: 'Con los cantos de sirena, no te vayas a marear.' },
  { n: 7, name: 'La Escalera', emoji: '🪜', verso: 'Súbeme paso a pasito, no quieras pegar brinquitos.' },
  { n: 8, name: 'La Botella', emoji: '🍾', verso: 'La herramienta del borracho.' },
  { n: 9, name: 'El Barril', emoji: '🛢️', verso: 'Tanto bebió el albañil, que quedó como barril.' },
  { n: 10, name: 'El Árbol', emoji: '🌳', verso: 'El que a buen árbol se arrima, buena sombra le cobija.' },
  { n: 11, name: 'El Melón', emoji: '🍈', verso: 'Me lo das o me lo quitas.' },
  { n: 12, name: 'El Valiente', emoji: '🗡️', verso: '¿Por qué le corres, cobarde, trayendo tan buen puñal?' },
  { n: 13, name: 'El Gorrito', emoji: '🧢', verso: 'Ponle su gorrito al nene, no se nos vaya a resfriar.' },
  { n: 14, name: 'La Muerte', emoji: '💀', verso: 'La muerte, tilica y flaca.' },
  { n: 15, name: 'La Pera', emoji: '🍐', verso: 'El que espera, desespera.' },
  { n: 16, name: 'La Bandera', emoji: '🇲🇽', verso: 'Verde, blanco y colorado, la bandera del soldado.' },
  { n: 17, name: 'El Bandolón', emoji: '🪕', verso: 'Tocando su bandolón está el mariachi Simón.' },
  { n: 18, name: 'El Violoncello', emoji: '🎻', verso: 'Creciendo se fue hasta el cielo, y como no fue violín, tuvo que ser violoncello.' },
  { n: 19, name: 'La Garza', emoji: '🦩', verso: 'Al otro lado del río tengo mi banco de arena, donde se sienta mi chata, pico de garza morena.' },
  { n: 20, name: 'El Pájaro', emoji: '🐦', verso: 'Tú me traes a puros brincos, como pájaro en la rama.' },
  { n: 21, name: 'La Mano', emoji: '✋', verso: 'La mano de un criminal.' },
  { n: 22, name: 'La Bota', emoji: '👢', verso: 'Una bota igual que la otra.' },
  { n: 23, name: 'La Luna', emoji: '🌙', verso: 'El farol de los enamorados.' },
  { n: 24, name: 'El Cotorro', emoji: '🦜', verso: 'Cotorro, cotorro, saca la pata y empiézame a platicar.' },
  { n: 25, name: 'El Borracho', emoji: '🥴', verso: '¡Qué borracho tan necio, ya no lo puedo aguantar!' },
  { n: 26, name: 'El Charro', emoji: '🤠', verso: 'Con sombrero y espuelas, el charro se va de fiesta.' },
  { n: 27, name: 'El Corazón', emoji: '❤️', verso: 'No me extrañes, corazón, que regreso en el camión.' },
  { n: 28, name: 'La Sandía', emoji: '🍉', verso: 'La barriga que Juan tenía era empacho de sandía.' },
  { n: 29, name: 'El Tambor', emoji: '🥁', verso: 'No te arrugues, cuero viejo, que te quiero pa’ tambor.' },
  { n: 30, name: 'El Camarón', emoji: '🦐', verso: 'Camarón que se duerme, se lo lleva la corriente.' },
  { n: 31, name: 'Las Jaras', emoji: '🏹', verso: 'Las jaras de Adán: donde pegan, dan.' },
  { n: 32, name: 'El Músico', emoji: '🎺', verso: 'El músico trompas de hule ya no me quiere tocar.' },
  { n: 33, name: 'La Araña', emoji: '🕷️', verso: 'Atarántamela a palos, no me la dejes llegar.' },
  { n: 34, name: 'El Soldado', emoji: '💂', verso: 'Uno, dos y tres, el soldado p’al cuartel.' },
  { n: 35, name: 'La Estrella', emoji: '⭐', verso: 'La guía de los marineros.' },
  { n: 36, name: 'El Cazo', emoji: '🥘', verso: 'El caso que te hago es poco.' },
  { n: 37, name: 'El Mundo', emoji: '🌎', verso: 'Este mundo es una bola, y nosotros un bolón.' },
  { n: 38, name: 'El Guerrero', emoji: '🪶', verso: 'El guerrero no se raja, ni en la guerra ni en la baraja.' },
  { n: 39, name: 'El Nopal', emoji: '🌵', verso: 'Al nopal lo van a ver nomás cuando tiene tunas.' },
  { n: 40, name: 'El Alacrán', emoji: '🦂', verso: 'El que con la cola pica, le dan una paliza.' },
  { n: 41, name: 'La Rosa', emoji: '🌹', verso: 'Rosita, Rosaura, ven que te quiero ahora.' },
  { n: 42, name: 'La Calavera', emoji: '☠️', verso: 'Al pasar por el panteón me encontré un calaverón.' },
  { n: 43, name: 'La Campana', emoji: '🔔', verso: 'Tú con la campana y yo con tu hermana.' },
  { n: 44, name: 'El Cantarito', emoji: '🏺', verso: 'Tanto va el cántaro al agua, que se quiebra y te moja las enaguas.' },
  { n: 45, name: 'El Venado', emoji: '🦌', verso: 'Saltando va buscando, pero no ve nada.' },
  { n: 46, name: 'El Sol', emoji: '☀️', verso: 'La cobija de los pobres.' },
  { n: 47, name: 'La Corona', emoji: '👑', verso: 'El sombrero de los reyes.' },
  { n: 48, name: 'La Chalupa', emoji: '🛶', verso: 'Rema que rema, Lupita, sentada en su chalupita.' },
  { n: 49, name: 'El Pino', emoji: '🌲', verso: 'Fresco y oloroso, en todo tiempo hermoso.' },
  { n: 50, name: 'El Pescado', emoji: '🐟', verso: 'El que por la boca muere, aunque mudo fuera.' },
  { n: 51, name: 'La Palma', emoji: '🌴', verso: 'Palmero, sube a la palma y bájame un coco real.' },
  { n: 52, name: 'La Maceta', emoji: '🪴', verso: 'El que nace pa’ maceta no sale del corredor.' },
  { n: 53, name: 'El Arpa', emoji: '🎼', verso: 'Arpa vieja de mi suegra, ya no sirves pa’ tocar.' },
  { n: 54, name: 'La Rana', emoji: '🐸', verso: 'Al ver a la verde rana, qué susto pegó tu hermana.' },
]

export type NuncaCard = { text: string; level: 'suave' | 'picante' }

const suave = (text: string): NuncaCard => ({ text, level: 'suave' })
const picante = (text: string): NuncaCard => ({ text, level: 'picante' })

export const YO_NUNCA: NuncaCard[] = [
  suave('Yo nunca he dicho “ahorita” sabiendo que no lo iba a hacer.'),
  suave('Yo nunca he comido tacos a las 3 de la mañana.'),
  suave('Yo nunca me he dormido en un vuelo con la boca abierta.'),
  suave('Yo nunca he perdido una maleta.'),
  suave('Yo nunca he llegado tarde a un vuelo.'),
  suave('Yo nunca he pedido algo en un restaurante sin saber qué era.'),
  suave('Yo nunca he fingido saber bailar salsa.'),
  suave('Yo nunca he cantado una ranchera a todo pulmón.'),
  suave('Yo nunca he llorado con una película de Pixar.'),
  suave('Yo nunca me he quemado con el sol en la playa por no ponerme bloqueador.'),
  suave('Yo nunca he probado chapulines.'),
  suave('Yo nunca he tomado tequila directo de la botella.'),
  suave('Yo nunca he mandado un audio de WhatsApp de más de 3 minutos.'),
  suave('Yo nunca he mandado un mensaje al grupo equivocado.'),
  suave('Yo nunca me he equivocado de día con un vuelo.'),
  suave('Yo nunca he usado Google Traductor para ligar.'),
  suave('Yo nunca he comido picante hasta llorar.'),
  suave('Yo nunca he visto una lucha libre en vivo.'),
  suave('Yo nunca he dicho “esta es la última” y pedí otra.'),
  suave('Yo nunca he olvidado el pasaporte en casa.'),
  suave('Yo nunca he hecho una siesta de más de 3 horas.'),
  suave('Yo nunca me he perdido en un aeropuerto.'),
  suave('Yo nunca he pagado el Uber de otro y nunca me lo devolvieron.'),
  suave('Yo nunca he stalkeado el Instagram de alguien de este grupo.'),
  suave('Yo nunca he fingido estar dormido para no ayudar.'),
  suave('Yo nunca he regateado en un mercado.'),
  suave('Yo nunca he comido algo que se cayó al piso (regla de los 5 segundos).'),
  suave('Yo nunca he pedido una canción al mariachi.'),
  suave('Yo nunca he bailado arriba de una mesa.'),
  suave('Yo nunca he nadado de noche en el mar.'),
  suave('Yo nunca he dicho “no manches” en voz alta en Suiza.'),
  suave('Yo nunca he usado la misma ropa tres días seguidos en un viaje.'),
  suave('Yo nunca he pedido comida a domicilio estando de vacaciones.'),
  suave('Yo nunca he tenido miedo de subirme a una lancha.'),
  suave('Yo nunca he dejado una reseña mala en internet.'),
  picante('Yo nunca he besado a alguien el mismo día que lo conocí.'),
  picante('Yo nunca he mandado un mensaje a mi ex estando pedo.'),
  picante('Yo nunca he tenido una cita por una app y me fui antes de tiempo.'),
  picante('Yo nunca he mentido sobre mi edad.'),
  picante('Yo nunca he despertado sin saber dónde estaba.'),
  picante('Yo nunca he tenido un crush con alguien de este grupo.'),
  picante('Yo nunca he entrado a un antro sin pagar.'),
  picante('Yo nunca he vomitado por tomar demasiado.'),
  picante('Yo nunca me he colado en una fiesta a la que no me invitaron.'),
  picante('Yo nunca he dado un beso en una fiesta de cumpleaños.'),
  picante('Yo nunca he dicho “te quiero” sin sentirlo.'),
  picante('Yo nunca he hecho un baile sexy para alguien.'),
  picante('Yo nunca me he bañado desnudo en el mar o en una alberca.'),
  picante('Yo nunca he borrado fotos de una fiesta para que nadie las viera.'),
  picante('Yo nunca he fingido una llamada para escaparme de alguien.'),
  picante('Yo nunca he ligado con alguien en un viaje.'),
  picante('Yo nunca he tenido una cruda que duró dos días.'),
  picante('Yo nunca le he revisado el celular a mi pareja.'),
  picante('Yo nunca he mandado una foto de la que me arrepentí.'),
  picante('Yo nunca me he quedado dormido en el baño de una fiesta.'),
  picante('Yo nunca he mentido en este juego.'),
  picante('Yo nunca he salido con dos personas al mismo tiempo.'),
  picante('Yo nunca he terminado con alguien por mensaje.'),
  picante('Yo nunca he usado la excusa del jet lag para no hacer algo.'),
  picante('Yo nunca he tomado mezcal hasta ver al gusano bailar.'),
  picante('Yo nunca he hecho algo en un viaje que no le contaría a mi mamá.'),
  picante('Yo nunca me he quitado la ropa en una fiesta.'),
]

export const VERDADES: string[] = [
  '¿Cuál es el plan de este viaje que más miedo te da?',
  '¿A quién del grupo llamarías si te arrestan en México?',
  '¿Qué es lo más vergonzoso que has hecho estando pedo?',
  '¿Cuál es tu crush famoso mexicano?',
  '¿Quién del grupo crees que va a perder algo primero?',
  '¿Cuál ha sido tu peor cita?',
  '¿Qué es lo más caro que has comprado y no usaste?',
  '¿Qué canción te da vergüenza que te guste?',
  '¿Quién del grupo baila peor?',
  '¿Qué es lo primero que harías si te ganas la lotería?',
  '¿Cuál es tu mayor miedo irracional?',
  '¿Cuál fue tu primera impresión de la persona a tu derecha?',
  '¿Qué es lo más raro que has comido?',
  '¿Cuál es el peor regalo que te han dado?',
  '¿Qué mentira dijiste para poder venir a este viaje?',
  '¿Qué app usas más y cuántas horas al día?',
  '¿Qué es lo que más te molesta de viajar en grupo?',
  '¿A quién del grupo le robarías el clóset?',
  '¿Cuál fue tu peor corte de pelo?',
  '¿Qué es lo más loco que has hecho por amor?',
  '¿Qué harías si te quedaras a vivir en México?',
  '¿Cuál es tu hábito más raro?',
  '¿Qué es algo que nunca le has contado a nadie del grupo?',
  '¿Quién del grupo es el más tacaño?',
  '¿Con quién del grupo no compartirías cuarto?',
  '¿Cuál es tu peor recuerdo de un viaje?',
  '¿Qué fue lo último que buscaste en Google?',
  '¿Cuál es tu placer culposo?',
  '¿Te has enamorado de alguien que no te hacía caso?',
  '¿Qué es lo más atrevido que has hecho en público?',
  '¿Cuál es el apodo más feo que te han puesto?',
  '¿Qué persona famosa te cae mal y por qué?',
  '¿Qué te regalarías para tu cumpleaños si fueras Pablo?',
  '¿Cuál ha sido tu cruda más fuerte?',
  '¿Qué harías con 24 horas sin reglas en Guadalajara?',
  '¿De qué te arrepientes de tus 20s?',
  '¿Quién del grupo sería el primero en sobrevivir a un apocalipsis zombie?',
  '¿Qué es lo más infantil que todavía haces?',
  '¿Cuál es tu red flag?',
  '¿Qué es lo que más te gusta de la persona a tu izquierda?',
  '¿Quién del grupo crees que se va a enfermar del estómago primero?',
  '¿Cuál es tu mejor anécdota de un viaje anterior con este grupo?',
]

export const RETOS: string[] = [
  'Pide una canción al mariachi y cántala con él.',
  'Habla con acento tapatío los próximos 10 minutos.',
  'Haz tu mejor entrada de luchador y preséntate con tu nombre de lucha.',
  'Imita a alguien del grupo hasta que adivinen quién es.',
  'Manda un audio al grupo cantando “Cielito lindo”.',
  'Pide la próxima orden de tacos solo con mímica.',
  'Deja que el grupo te escriba un estado de WhatsApp.',
  'Baila 30 segundos sin música.',
  'Di un piropo mexicano a la persona de tu derecha.',
  'Tómate una selfie con un desconocido (con permiso).',
  'Háblale en inglés con acento texano al mesero.',
  'Haz 15 sentadillas mientras dices “¡Viva México!”.',
  'Cuenta un chiste; si nadie se ríe, otro reto.',
  'Grita “¡Luchaaa!” como si estuvieras en la Arena.',
  'Deja que alguien te ponga un apodo para el resto del día.',
  'Invita una ronda de chelas (o de aguas frescas) al grupo.',
  'Haz una declaración de amor dramática a tu taco.',
  'Imita a un vendedor del mercado vendiendo tu celular.',
  'Canta el “Happy Birthday” en versión ranchera para Pablo.',
  'Usa tus lentes de sol al revés durante 10 minutos.',
  'Narra lo que hace el grupo como comentarista de fútbol durante 1 minuto.',
  'Aprende y di 3 mexicanismos nuevos en una frase.',
  'Dale un masaje de hombros de 1 minuto a quien elija el grupo.',
  'Escribe un poema de 4 versos sobre el guacamole.',
  'Pide un shot de algo que nunca hayas probado.',
  'Deja que el grupo elija tu próximo platillo.',
  'Haz la pose de la foto más ridícula que se te ocurra y súbela a una historia.',
  'Camina como pato hasta la otra punta del cuarto.',
  'Habla solo cantando los próximos 3 minutos.',
  'Llama a alguien de tu familia y dile “¡ya me voy a quedar a vivir en México!”.',
  'Muestra la última foto de tu galería.',
  'Haz un TikTok bailando con la persona que elija el grupo.',
  'Aguanta la risa mientras todos intentan hacerte reír por 30 segundos.',
  'Pide la cuenta con la frase más elegante posible.',
  'Pon la canción que elija el grupo y báilala con todo.',
  'Di 5 cosas bonitas de la persona que tienes enfrente.',
  'Ponte como luchador una máscara imaginaria y no te la quites hasta tu próximo turno.',
  'Traduce al español mexicano una frase en suizo alemán.',
  'Haz de guía turístico por 1 minuto del lugar donde están.',
  'Brinda con todo el grupo con un discurso de 30 segundos.',
  'Haz tu mejor grito de mariachi: ¡Ay, ay, ay!',
  'El próximo Uber lo pides tú… y lo pagas tú.',
]

export type TriviaQ = { q: string; options: string[]; answer: number; why: string }

export const TRIVIA: TriviaQ[] = [
  { q: '¿Cuál es la capital de Jalisco?', options: ['Guadalajara', 'Zapopan', 'Puerto Vallarta', 'Tlaquepaque'], answer: 0, why: 'Guadalajara, la “Perla de Occidente”, es la capital de Jalisco.' },
  { q: '¿De qué planta se hace el tequila?', options: ['Maguey pulquero', 'Agave azul', 'Nopal', 'Caña de azúcar'], answer: 1, why: 'El tequila se hace con agave azul (Agave tequilana Weber).' },
  { q: '¿Cuál es la pirámide más grande de Teotihuacán?', options: ['De la Luna', 'Del Sol', 'De Quetzalcóatl', 'De Kukulcán'], answer: 1, why: 'La Pirámide del Sol mide unos 65 m de alto.' },
  { q: '¿A qué altura aproximada está la Ciudad de México?', options: ['800 m', '1.500 m', '2.240 m', '3.100 m'], answer: 2, why: 'CDMX está a unos 2.240 m sobre el nivel del mar: ¡ojo con las chelas el primer día!' },
  { q: '¿Qué empresa de lucha libre, fundada en 1933, es la más antigua del mundo?', options: ['AAA', 'WWE', 'CMLL', 'Lucha Underground'], answer: 2, why: 'El Consejo Mundial de Lucha Libre (CMLL) nació en 1933.' },
  { q: '¿De qué estado es originario el mariachi?', options: ['Oaxaca', 'Jalisco', 'Veracruz', 'Sonora'], answer: 1, why: 'El mariachi nació en Jalisco y es Patrimonio Cultural Inmaterial de la UNESCO desde 2011.' },
  { q: '¿En qué barrio de CDMX está la Casa Azul de Frida Kahlo?', options: ['Polanco', 'Coyoacán', 'Condesa', 'Xochimilco'], answer: 1, why: 'La Casa Azul está en Coyoacán, donde Frida nació y murió.' },
  { q: '¿En qué bahía está Puerto Vallarta?', options: ['Bahía de Banderas', 'Bahía de La Paz', 'Bahía de Acapulco', 'Bahía Magdalena'], answer: 0, why: 'Vallarta está en la Bahía de Banderas, una de las más grandes de México.' },
  { q: '¿A qué estado pertenecen las Islas Marietas?', options: ['Jalisco', 'Colima', 'Nayarit', 'Sinaloa'], answer: 2, why: 'Aunque se visitan desde Vallarta, las Marietas pertenecen a Nayarit.' },
  { q: '¿Cuál es la capital de Baja California Sur?', options: ['Los Cabos', 'Loreto', 'La Paz', 'Todos Santos'], answer: 2, why: 'La Paz es la capital de Baja California Sur.' },
  { q: '¿A qué mar mira La Paz?', options: ['Mar Caribe', 'Mar de Cortés', 'Golfo de México', 'Mar de Bering'], answer: 1, why: 'La Paz está sobre el Mar de Cortés (Golfo de California).' },
  { q: '¿Cómo llamó Jacques Cousteau al Mar de Cortés?', options: ['La alberca del mundo', 'El acuario del mundo', 'El mar azul', 'El jardín del mar'], answer: 1, why: 'Cousteau lo llamó “el acuario del mundo” por su biodiversidad.' },
  { q: '¿Dónde está El Arco?', options: ['Cabo San Lucas', 'Tulum', 'Acapulco', 'Mazatlán'], answer: 0, why: 'El Arco está en Cabo San Lucas, donde se juntan el Pacífico y el Mar de Cortés.' },
  { q: '¿De qué ciudad es típica la torta ahogada?', options: ['Monterrey', 'Puebla', 'Guadalajara', 'Mérida'], answer: 2, why: 'La torta ahogada, bañada en salsa, es tapatía de corazón.' },
  { q: '¿De qué estado son los chiles en nogada?', options: ['Puebla', 'Yucatán', 'Chiapas', 'Nuevo León'], answer: 0, why: 'Son de Puebla y llevan los colores de la bandera.' },
  { q: '¿Cuándo se celebra el Día de Muertos?', options: ['31 de octubre', '1 y 2 de noviembre', '12 de diciembre', '16 de septiembre'], answer: 1, why: 'Se celebra el 1 (niños) y el 2 de noviembre (adultos).' },
  { q: '¿Qué día se celebra la Independencia de México?', options: ['5 de mayo', '16 de septiembre', '20 de noviembre', '24 de febrero'], answer: 1, why: 'El 16 de septiembre; el “Grito” es la noche del 15. El 5 de mayo es la batalla de Puebla.' },
  { q: '¿Cómo se llamaba la capital mexica sobre la que se construyó CDMX?', options: ['Teotihuacán', 'Tenochtitlan', 'Chichén Itzá', 'Tula'], answer: 1, why: 'Tenochtitlan fue fundada en 1325 sobre el lago de Texcoco.' },
  { q: '¿Cuántas entidades federativas tiene México?', options: ['28', '30', '32', '35'], answer: 2, why: '31 estados + la Ciudad de México = 32.' },
  { q: '¿Qué equipo de Guadalajara solo juega con futbolistas mexicanos?', options: ['Atlas', 'Chivas', 'Leones Negros', 'Tapatío'], answer: 1, why: 'Las Chivas del Guadalajara son famosas por jugar solo con mexicanos.' },
  { q: '¿Cuál es el apodo del Atlas?', options: ['Los Zorros', 'Los Tuzos', 'Los Gallos', 'Los Rayados'], answer: 0, why: 'Al Atlas le dicen “los Zorros” (o la Academia).' },
  { q: '¿Qué estadio de CDMX inauguró el Mundial 2026?', options: ['Estadio Olímpico Universitario', 'Estadio Azteca', 'Estadio Jalisco', 'Estadio BBVA'], answer: 1, why: 'El Estadio Azteca, el único que ha albergado inauguraciones de tres Mundiales (1970, 1986 y 2026).' },
  { q: '¿De qué estado viene la mayor parte del mezcal?', options: ['Oaxaca', 'Jalisco', 'Baja California', 'Quintana Roo'], answer: 0, why: 'Oaxaca produce la gran mayoría del mezcal del país.' },
  { q: '¿Quién pintó los murales del Hospicio Cabañas en Guadalajara?', options: ['Diego Rivera', 'David Alfaro Siqueiros', 'José Clemente Orozco', 'Rufino Tamayo'], answer: 2, why: 'Orozco; su “Hombre de fuego” está en la cúpula. Es Patrimonio de la UNESCO desde 1997.' },
  { q: '¿Con quién estaba casada Frida Kahlo?', options: ['Diego Rivera', 'Octavio Paz', 'Pedro Infante', 'Juan Rulfo'], answer: 0, why: 'Frida se casó dos veces con el muralista Diego Rivera.' },
  { q: '¿Qué ingrediente NO es originario de América?', options: ['Aguacate', 'Tomate', 'Arroz', 'Maíz'], answer: 2, why: 'El arroz llegó de Asia; el aguacate, el tomate y el maíz son de aquí.' },
  { q: '¿Qué animal endémico vive en los canales de Xochimilco?', options: ['Manatí', 'Ajolote', 'Jaguar', 'Axis'], answer: 1, why: 'El ajolote, que regenera sus extremidades, vive (poco) en Xochimilco.' },
  { q: '¿Cómo le dicen de cariño al volcán Popocatépetl?', options: ['Don Goyo', 'El Popo Loco', 'Don Chucho', 'El Abuelo'], answer: 0, why: 'Le dicen “Don Goyo”. Popocatépetl significa “cerro que humea”.' },
  { q: '¿Qué son los chapulines?', options: ['Chiles secos', 'Saltamontes', 'Tortillas pequeñas', 'Hormigas'], answer: 1, why: 'Chapulines = saltamontes tostados con limón, sal y chile.' },
  { q: '¿Qué hace brillar el mar de noche en la bioluminiscencia?', options: ['Medusas eléctricas', 'Algas y plancton (dinoflagelados)', 'Reflejo de la luna', 'Minerales'], answer: 1, why: 'Microorganismos llamados dinoflagelados emiten luz al moverse el agua.' },
  { q: '¿Cuál es el pez más grande del mundo, que visita la bahía de La Paz?', options: ['Mantarraya', 'Tiburón blanco', 'Tiburón ballena', 'Pez vela'], answer: 2, why: 'El tiburón ballena puede medir más de 12 m y solo come plancton.' },
  { q: '¿Qué diferencia horaria tiene La Paz respecto a CDMX?', options: ['La misma hora', '1 hora menos', '2 horas menos', '1 hora más'], answer: 1, why: 'Baja California Sur va 1 hora por detrás de CDMX.' },
  { q: '¿De qué plato viene la inspiración del taco al pastor?', options: ['Kebab turco', 'Shawarma libanés', 'Gyros griego', 'Asado argentino'], answer: 1, why: 'Inmigrantes libaneses trajeron el trompo de shawarma; en México se volvió pastor.' },
  { q: '“Ay, ay, ay, ay, canta y no llores…” ¿Qué canción es?', options: ['La Bamba', 'Cielito lindo', 'El Rey', 'Guadalajara'], answer: 1, why: 'Es “Cielito lindo”, de Quirino Mendoza y Cortés (1882).' },
  { q: '¿En qué pueblo está la destilería La Rojeña de José Cuervo?', options: ['Amatitán', 'Tequila', 'Arandas', 'Tlaquepaque'], answer: 1, why: 'Está en Tequila, Jalisco, y es la destilería activa más antigua de América Latina (1812).' },
  { q: '¿Qué significa “águila o sol” al lanzar una moneda?', options: ['Cara o cruz', 'Par o impar', 'Arriba o abajo', 'Ganar o perder'], answer: 0, why: 'Águila es el lado del escudo nacional; sol, el del valor.' },
  { q: '¿Qué es un “tianguis”?', options: ['Un baile típico', 'Un mercado callejero', 'Un tipo de taco', 'Un sombrero'], answer: 1, why: 'Viene del náhuatl tianquiztli: mercado.' },
  { q: '¿Cuántas lenguas indígenas reconoce oficialmente México?', options: ['12', '35', '68', '120'], answer: 2, why: 'El INALI reconoce 68 lenguas indígenas, además del español.' },
]

/** Casillas del bingo: 24 retos + la casilla libre al centro (índice 12) */
export const BINGO_CELLS: { emoji: string; text: string }[] = [
  { emoji: '🎺', text: 'Ver un mariachi en vivo' },
  { emoji: '🦗', text: 'Comer chapulines' },
  { emoji: '🦭', text: 'Ver un lobo marino' },
  { emoji: '😱', text: 'Alguien dice “no manches”' },
  { emoji: '🕺', text: 'Pablo bailando' },
  { emoji: '🥖', text: 'Probar una torta ahogada' },
  { emoji: '🔺', text: 'Subir a las pirámides' },
  { emoji: '🌉', text: 'Selfie en El Arco' },
  { emoji: '🙈', text: 'Alguien pierde algo' },
  { emoji: '🥃', text: 'Tomar mezcal' },
  { emoji: '🪢', text: 'Ver a los voladores de Papantla' },
  { emoji: '🤼', text: 'Gritar “¡Lucha!” en la Arena' },
  { emoji: '🇲🇽', text: 'Libre' },
  { emoji: '🏖️', text: 'Nadar en Balandra' },
  { emoji: '✨', text: 'Ver la bioluminiscencia' },
  { emoji: '🌮', text: 'Taco a las 3 am' },
  { emoji: '🌶️', text: 'Llorar por el picante' },
  { emoji: '🎂', text: 'Cantar Las Mañanitas' },
  { emoji: '🛶', text: 'Subir a una lancha' },
  { emoji: '🌅', text: 'Ver el atardecer en el mar' },
  { emoji: '🤠', text: 'Ponerse un sombrero' },
  { emoji: '⚽', text: 'Gritar un gol en el estadio' },
  { emoji: '💤', text: 'Siesta en la playa' },
  { emoji: '🗣️', text: 'Hablar con un local 5 min' },
  { emoji: '🥑', text: 'Guacamole hecho en molcajete' },
]
export const BINGO_FREE = 12
